.PHONY: iu5, sgn3
	
iu5:
	python gen.py \
		--title="Разработка интернет-приложений" \
		--date=12.12.2017 \
		--groups=py,py+,frontend,django,js \
		--out=tickets-iu5.docx

sgn3:
	python gen.py \
		--title="Языки интернет-программирования" \
		--date=12.12.2017 \
		--groups=py,py+,django,ml \
		--out=tickets-sgn3.docx
